spring.application.name=proxy-service
server.port=8082

# ==========================
# Kafka – cátedra
# ==========================
spring.kafka.bootstrap-servers=192.168.194.250:9092

# Usá un group-id único para vos
spring.kafka.consumer.group-id=gestioneventos-renzo
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Tópicos de trabajo (ajustá los nombres a los reales que te haya dado la cátedra)
app.kafka.topic.eventos=eventos
app.kafka.topic.asientos=asientos
app.kafka.topic.reservas=reservas

# ==========================
# Redis – cátedra
# ==========================
spring.data.redis.host=192.168.194.250
spring.data.redis.port=6379
spring.data.redis.timeout=5000


