package ar.edu.um.gestioneventos.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SesionUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioAllPropertiesEquals(SesionUsuario expected, SesionUsuario actual) {
        assertSesionUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertSesionUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioAllUpdatablePropertiesEquals(SesionUsuario expected, SesionUsuario actual) {
        assertSesionUsuarioUpdatableFieldsEquals(expected, actual);
        assertSesionUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertSesionUsuarioMapsIdRelationshipPersistedValue(SesionUsuario entityToPersist, SesionUsuario persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioAutoGeneratedPropertiesEquals(SesionUsuario expected, SesionUsuario actual) {
        assertThat(actual)
            .as("Verify SesionUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioUpdatableFieldsEquals(SesionUsuario expected, SesionUsuario actual) {
        assertThat(actual)
            .as("Verify SesionUsuario relevant properties")
            .satisfies(a -> assertThat(a.getEstadoFlujo()).as("check estadoFlujo").isEqualTo(expected.getEstadoFlujo()))
            .satisfies(a -> assertThat(a.getDatosTemporales()).as("check datosTemporales").isEqualTo(expected.getDatosTemporales()))
            .satisfies(a ->
                assertThat(a.getUltimaActualizacion()).as("check ultimaActualizacion").isEqualTo(expected.getUltimaActualizacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioUpdatableRelationshipsEquals(SesionUsuario expected, SesionUsuario actual) {
        // empty method
    }
}
